---
title: "R Notebook"
output: html_notebook
---

```{r}
# load counts table from GEO
urld3 <- "https://www.ncbi.nlm.nih.gov/geo/download/?format=file&type=rnaseq_counts"
path3 <- paste(urld3, "acc=GSE199225", "file=GSE199225_raw_counts_GRCh38.p13_NCBI.tsv.gz", sep="&");
tbl3 <- as.matrix(data.table::fread(path3, header=T, colClasses="integer"), rownames="GeneID")
```

```{r}
# load gene annotations 
apath3 <- paste(urld3, "type=rnaseq_counts", "file=Human.GRCh38.p13.annot.tsv.gz", sep="&")
annot3 <- data.table::fread(apath3, header=T, quote="", stringsAsFactors=F, data.table=F)
rownames(annot3) <- annot3$GeneID
```
```{r}
# sample selection
gsms3 <- "XXXXXXXXXX000000000000000XXXXXXXXXXXXXXXX111111111111111XXXXX"
sml3 <- strsplit(gsms3, split="")[[1]]
```

```{r}
# filter out excluded samples (marked as "X")
sel3 <- which(sml3 != "X")
sml3 <- sml3[sel3]
tbl3 <- tbl3[ ,sel3]

# group membership for samples
gs3 <- factor(sml3)
groups3 <- make.names(c("CTRL","PCOS"))
levels(gs3) <- groups3
sample_info3 <- data.frame(Group = gs3, row.names = colnames(tbl3))
```

```{r}
# pre-filter low count genes
# keep genes with at least N counts > 10, where N = size of smallest group
keep3 <- rowSums(tbl3 >= 10 ) >= min(table(gs3))
tbl3 <- tbl3[keep3, ]

#   Differential expression analysis with DESeq2

library(DESeq2)

ds3 <- DESeqDataSetFromMatrix(countData=tbl3, colData=sample_info3, design= ~Group)
ds3 <- DESeq(ds3, test="Wald", sfType="poscount")
dat3 <- log10(counts(ds3, normalized = T) + 1) # extract normalized counts
write.csv(dat3, "data_exprs_GSE199225_EPS.csv")
```

```{r}
# extract results for top genes table
r3 <- results (ds3, contrast=c("Group", groups3[1], groups3[2]), alpha=0.05, pAdjustMethod ="fdr")

tT3 <- r3[order(r3$padj),] 
tT3 <- merge(as.data.frame(tT3), annot3, by=0, sort=F)

tT3 <- subset(tT3, select=c("GeneID","padj","pvalue","lfcSE","stat","log2FoldChange","baseMean","Symbol","Description"))
write.table(tT3, file=stdout(), row.names=F, sep="\t")
write.csv(tT3, "results_of_DEGs_GSE199225_EPS.csv")

```










